name: Build APK (show deprecations)

on:
  workflow_dispatch: # run manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x android/gradlew || chmod +x gradlew

      - name: Build APK
        run: |
          if [ -f "gradlew" ]; then
            ./gradlew assembleDebug --warning-mode all
          else
            cd android && ./gradlew assembleDebug --warning-mode all
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: fcm-token-viewer-apk
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            android/app/build/outputs/apk/debug/app-debug.apk
